// NativeMenu_as.hx:  ActionScript 3 "NativeMenu" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090514 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009, 2010 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.display.NativeMenu;
import flash.display.MovieClip;
#else
import flash.NativeMenu;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class NativeMenu_as {
    static function main() {
        var x1:NativeMenu = new NativeMenu();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("NativeMenu class exists");
        } else {
            DejaGnu.fail("NativeMenu lass doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.items == 0) {
	    DejaGnu.pass("NativeMenu::items property exists");
	} else {
	    DejaGnu.fail("NativeMenu::items property doesn't exist");
	}
	if (x1.numItems == 0) {
	    DejaGnu.pass("NativeMenu::numItems property exists");
	} else {
	    DejaGnu.fail("NativeMenu::numItems property doesn't exist");
	}
	if (x1.parent == NativeMenu) {
	    DejaGnu.pass("NativeMenu::parent property exists");
	} else {
	    DejaGnu.fail("NativeMenu::parent property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.addItem == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::addItem() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::addItem() method doesn't exist");
	}
	if (x1.addItemAt == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::addItemAt() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::addItemAt() method doesn't exist");
	}
	if (x1.addSubmenu == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::addSubmenu() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::addSubmenu() method doesn't exist");
	}
	if (x1.addSubmenuAt == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::addSubmenuAt() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::addSubmenuAt() method doesn't exist");
	}
	if (x1.clone == NativeMenu) {
	    DejaGnu.pass("NativeMenu::clone() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::clone() method doesn't exist");
	}
	if (x1.containsItem == false) {
	    DejaGnu.pass("NativeMenu::containsItem() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::containsItem() method doesn't exist");
	}
	if (x1.display == null) {
	    DejaGnu.pass("NativeMenu::display() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::display() method doesn't exist");
	}
	if (x1.getItemAt == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::getItemAt() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::getItemAt() method doesn't exist");
	}
	if (x1.getItemByName == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::getItemByName() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::getItemByName() method doesn't exist");
	}
	if (x1.getItemIndex == 0) {
	    DejaGnu.pass("NativeMenu::getItemIndex() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::getItemIndex() method doesn't exist");
	}
	if (x1.removeAllItems == null) {
	    DejaGnu.pass("NativeMenu::removeAllItems() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::removeAllItems() method doesn't exist");
	}
	if (x1.removeItem == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::removeItem() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::removeItem() method doesn't exist");
	}
	if (x1.removeItemAt == NativeMenuItem) {
	    DejaGnu.pass("NativeMenu::removeItemAt() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::removeItemAt() method doesn't exist");
	}
	if (x1.setItemIndex == null) {
	    DejaGnu.pass("NativeMenu::setItemIndex() method exists");
	} else {
	    DejaGnu.fail("NativeMenu::setItemIndex() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

