// Generated by Makefile, don't hand edit!
#ifndef GNASH_ASOBJ_FLASH_FILTERS_H
#define GNASH_ASOBJ_FLASH_FILTERS_H 1
#include "sharedlib.h"
static gnash::SharedLib::initentry *filtersclasses[] = {
	gnash::bevelfilter_class_init,
	gnash::bitmapfilterquality_class_init,
	gnash::bitmapfiltertype_class_init,
	gnash::bitmapfilter_class_init,
	gnash::blurfilter_class_init,
	gnash::colormatrixfilter_class_init,
	gnash::convolutionfilter_class_init,
	gnash::displacementmapfiltermode_class_init,
	gnash::displacementmapfilter_class_init,
	gnash::dropshadowfilter_class_init,
	gnash::glowfilter_class_init,
	gnash::gradientbevelfilter_class_init,
	gnash::gradientglowfilter_class_init,
	0
};
#endif // end of GNASH_ASOBJ_FLASH_FILTERS_H
