// Generated by Makefile, don't hand edit!
#ifndef GNASH_ASOBJ_FLASH_FILTERS_H
#define GNASH_ASOBJ_FLASH_FILTERS_H 1
#include "sharedlib.h"
static gnash::SharedLib::initentry *filtersclasses[] = {
	0
};
#endif // end of GNASH_ASOBJ_FLASH_FILTERS_H
