// ColorMatrixFilter_as.hx:  ActionScript 3 "ColorMatrixFilter" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009, 2010 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.filters.ColorMatrixFilter;
import flash.display.MovieClip;
#else
import flash.filters.ColorMatrixFilter;
import flash.MovieClip;
#end
import flash.Lib;
import Type;
import Std;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class ColorMatrixFilter_as {
    static function main() {
        var x1:ColorMatrixFilter = new ColorMatrixFilter();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("ColorMatrixFilter class exists");
        } else {
            DejaGnu.fail("ColorMatrixFilter class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (Std.is(x1.matrix, Array)) {
	    DejaGnu.pass("ColorMatrixFilter.matrix property exists");
	} else {
	    DejaGnu.fail("ColorMatrixFilter.matrix property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (Type.TypeOf(x1.clone) == ValueType.TFunction) {
	    DejaGnu.pass("ColorMatrixFilter::clone() method exists");
	} else {
	    DejaGnu.fail("ColorMatrixFilter::clone() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

