// 
//   Copyright (C) 2007, 2008, 2009 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// A file to contain all of the different strings for which we want compile time
// known string table keys.

#ifdef HAVE_CONFIG_H
#include "gnashconfig.h"
#endif

#include "namedStrings.h"
#include "string_table.h"

namespace gnash {
namespace NSV { // Named String Values

// Load up our pre-known names
static string_table::svt preload_names[] =
{
	string_table::svt( "a", NSV::PROP_A ),
	string_table::svt( "addListener", NSV::PROP_ADD_LISTENER ),
	string_table::svt( "align", NSV::PROP_ALIGN ),
	string_table::svt( "_alpha", NSV::PROP_uALPHA ),
	string_table::svt( "b", NSV::PROP_B ),
	string_table::svt( "blockIndent", NSV::PROP_BLOCK_INDENT ),
	string_table::svt( "bold", NSV::PROP_BOLD ),
	string_table::svt( "broadcastMessage", NSV::PROP_BROADCAST_MESSAGE ),
	string_table::svt( "bullet", NSV::PROP_BULLET ),
	string_table::svt( "c", NSV::PROP_C ),
	string_table::svt( "callee", NSV::PROP_CALLEE ),
	string_table::svt( "caller", NSV::PROP_CALLER ),
	//string_table::svt( "color", NSV::PROP_COLOR ), // clashes with CLASS_COLOR in case-insensitive mode
	string_table::svt( "concat", NSV::PROP_CONCAT ),	
	string_table::svt( "constructor", NSV::PROP_CONSTRUCTOR ),
	string_table::svt( "__constructor__", NSV::PROP_uuCONSTRUCTORuu ),
	string_table::svt( "contentType", NSV::PROP_CONTENT_TYPE),
	string_table::svt( "_currentframe", NSV::PROP_uCURRENTFRAME ),
	string_table::svt( "_customHeaders", NSV::PROP_uCUSTOM_HEADERS ),
	string_table::svt( "d", NSV::PROP_D ),
	string_table::svt( "data", NSV::PROP_DATA ),
	string_table::svt( "decode", NSV::PROP_DECODE ),
	string_table::svt( "e", NSV::PROP_E ),	
	string_table::svt( "escape", NSV::PROP_ESCAPE ),	
	string_table::svt( "_droptarget", NSV::PROP_uDROPTARGET ),
	string_table::svt( "enabled", NSV::PROP_ENABLED ),
	string_table::svt( "useHandCursor", NSV::PROP_USEHANDCURSOR ),
	string_table::svt( "focusEnabled", NSV::PROP_FOCUS_ENABLED ),	
	string_table::svt( "_focusrect", NSV::PROP_uFOCUSRECT ),
	string_table::svt( "_framesloaded", NSV::PROP_uFRAMESLOADED ),
	string_table::svt( "_height", NSV::PROP_uHEIGHT ),
        string_table::svt( "g", NSV::PROP_G ),
        string_table::svt( "h", NSV::PROP_H ),
	string_table::svt( "height", NSV::PROP_HEIGHT ),
	string_table::svt( "_highquality", NSV::PROP_uHIGHQUALITY ),
	string_table::svt( "_quality", NSV::PROP_uQUALITY ),
	string_table::svt( "htmlText", NSV::PROP_HTML_TEXT ),
	string_table::svt( "indent", NSV::PROP_INDENT ),
	string_table::svt( "italic", NSV::PROP_ITALIC ),
	string_table::svt( "leading", NSV::PROP_LEADING ),
	string_table::svt( "left_margin", NSV::PROP_LEFT_MARGIN ),
	string_table::svt( "length", NSV::PROP_LENGTH ),
	string_table::svt( "_listeners", NSV::PROP_uLISTENERS ),
	string_table::svt( "loaded", NSV::PROP_LOADED ),
	string_table::svt( "matrixType", NSV::PROP_MATRIX_TYPE),
	string_table::svt( "meth", NSV::PROP_METH),
	string_table::svt( "_name", NSV::PROP_uNAME ),
	string_table::svt( "onLoad", NSV::PROP_ON_LOAD ),
	string_table::svt( "onClose", NSV::PROP_ON_CLOSE ),
	string_table::svt( "onLoadStart", NSV::PROP_ON_LOAD_START ),
	string_table::svt( "onLoadError", NSV::PROP_ON_LOAD_ERROR ),
	string_table::svt( "onLoadProgress", NSV::PROP_ON_LOAD_PROGRESS ),
	string_table::svt( "onLoadInit", NSV::PROP_ON_LOAD_INIT ),
        string_table::svt( "onSoundComplete", NSV::PROP_ON_SOUND_COMPLETE ),
	string_table::svt( "onUnload", NSV::PROP_ON_UNLOAD ),
	string_table::svt( "onEnterFrame", NSV::PROP_ON_ENTER_FRAME ),
	string_table::svt( "onConstruct", NSV::PROP_ON_CONSTRUCT ),
	string_table::svt( "onInitialize", NSV::PROP_ON_INITIALIZE ),
	string_table::svt( "onData", NSV::PROP_ON_DATA ),
	string_table::svt( "onResize", NSV::PROP_ON_RESIZE ),
	string_table::svt( "onFullScreen", NSV::PROP_ON_FULLSCREEN ),
	string_table::svt( "onPress", NSV::PROP_ON_PRESS ),
	string_table::svt( "onRelease", NSV::PROP_ON_RELEASE ),
	string_table::svt( "onReleaseOutside", NSV::PROP_ON_RELEASE_OUTSIDE ),
	string_table::svt( "onRollOut", NSV::PROP_ON_ROLL_OUT ),
	string_table::svt( "onRollOver", NSV::PROP_ON_ROLL_OVER ),
	string_table::svt( "onDragOver", NSV::PROP_ON_DRAG_OVER ),
	string_table::svt( "onDragOut", NSV::PROP_ON_DRAG_OUT ),
	string_table::svt( "onKeyPress", NSV::PROP_ON_KEY_PRESS ),
	string_table::svt( "onKeyDown", NSV::PROP_ON_KEY_DOWN ),
	string_table::svt( "onKeyUp", NSV::PROP_ON_KEY_UP ),
	string_table::svt( "onMouseDown", NSV::PROP_ON_MOUSE_DOWN ),
	string_table::svt( "onMouseUp", NSV::PROP_ON_MOUSE_UP ),
	string_table::svt( "onMouseMove", NSV::PROP_ON_MOUSE_MOVE ),
	string_table::svt( "onSetFocus", NSV::PROP_ON_SET_FOCUS ),
	string_table::svt( "onKillFocus", NSV::PROP_ON_KILL_FOCUS ),
	string_table::svt( "onSelect", NSV::PROP_ON_SELECT ),
	string_table::svt( "onStatus", NSV::PROP_ON_STATUS ),
	string_table::svt( "onResult", NSV::PROP_ON_RESULT ),
	string_table::svt( "onMetaData", NSV::PROP_ON_META_DATA ),
	string_table::svt( "onConnect", NSV::PROP_ON_CONNECT ),
        string_table::svt( "onXML", NSV::PROP_ON_XML ),
	string_table::svt( "parseXML", NSV::PROP_PARSE_XML ),
	string_table::svt( "onTimer", NSV::PROP_ON_TIMER ),
	string_table::svt( "_parent", NSV::PROP_uPARENT ),
	string_table::svt( "_root", NSV::PROP_uROOT ),
	string_table::svt( "_global", NSV::PROP_uGLOBAL ),
	string_table::svt( "__proto__", NSV::PROP_uuPROTOuu ),
	string_table::svt( "prototype", NSV::PROP_PROTOTYPE ),
	string_table::svt( "push", NSV::PROP_PUSH ),
	string_table::svt( "__resolve", NSV::PROP_uuRESOLVE ),
	string_table::svt( "r", NSV::PROP_R ),
	string_table::svt( "removeListener", NSV::PROP_REMOVE_LISTENER ),
	string_table::svt( "rightMargin", NSV::PROP_RIGHT_MARGIN ),
	string_table::svt( "_rotation", NSV::PROP_uROTATION ),
	string_table::svt( "scaleMode", NSV::PROP_SCALE_MODE ),
	string_table::svt( "size", NSV::PROP_SIZE ),
	string_table::svt( "_soundbuftime", NSV::PROP_uSOUNDBUFTIME ),
	string_table::svt( "splice", NSV::PROP_SPLICE ),
	string_table::svt( "Stage", NSV::PROP_iSTAGE ),
	string_table::svt( "status", NSV::PROP_STATUS ),
	string_table::svt( "super", NSV::PROP_SUPER ),
	string_table::svt( "_target", NSV::PROP_uTARGET ),
	string_table::svt( "text", NSV::PROP_TEXT ),
	string_table::svt( "textColor", NSV::PROP_TEXT_COLOR ),
	string_table::svt( "textWidth", NSV::PROP_TEXT_WIDTH ),
	string_table::svt( "textHeight", NSV::PROP_TEXT_HEIGHT ),
	string_table::svt( "toString", NSV::PROP_TO_STRING ),
	string_table::svt( "toLowerCase", NSV::PROP_TO_LOWER_CASE ),
	string_table::svt( "_totalframes", NSV::PROP_uTOTALFRAMES ),
	string_table::svt( "tx", NSV::PROP_TX ),
	string_table::svt( "ty", NSV::PROP_TY ),
	string_table::svt( "underline", NSV::PROP_UNDERLINE ),
	string_table::svt( "_url", NSV::PROP_uURL ),
	string_table::svt( "valueOf", NSV::PROP_VALUE_OF ),
	string_table::svt( "_visible", NSV::PROP_uVISIBLE ),
	string_table::svt( "w", NSV::PROP_W ),
	string_table::svt( "_width", NSV::PROP_uWIDTH ),
	string_table::svt( "width", NSV::PROP_WIDTH ),
	string_table::svt( "x", NSV::PROP_X ),
	string_table::svt( "_x", NSV::PROP_uX ),
	string_table::svt( "_xmouse", NSV::PROP_uXMOUSE ),
	string_table::svt( "_xscale", NSV::PROP_uXSCALE ),
	string_table::svt( "y", NSV::PROP_Y ),
	string_table::svt( "_y", NSV::PROP_uY ),
	string_table::svt( "_ymouse", NSV::PROP_uYMOUSE ),
	string_table::svt( "_yscale", NSV::PROP_uYSCALE ),
#if 0
	string_table::svt( "System", NSV::CLASS_SYSTEM ),
//	string_table::svt( "Stage", NSV::CLASS_STAGE ), // Identical to PROP_iSTAGE
	string_table::svt( "MovieClip", NSV::CLASS_MOVIE_CLIP ),
	string_table::svt( "TextField", NSV::CLASS_TEXT_FIELD ),
	string_table::svt( "Button", NSV::CLASS_BUTTON ),
	string_table::svt( "Math", NSV::CLASS_MATH ),
	string_table::svt( "Boolean", NSV::CLASS_BOOLEAN ),
	string_table::svt( "Color", NSV::CLASS_COLOR ),
	string_table::svt( "Selection", NSV::CLASS_SELECTION ),
	string_table::svt( "Sound", NSV::CLASS_SOUND ),
	string_table::svt( "XMLSocket", NSV::CLASS_XMLSOCKET ),
	string_table::svt( "Date", NSV::CLASS_DATE ),
	string_table::svt( "XML", NSV::CLASS_XML ),
	string_table::svt( "XMLNode", NSV::CLASS_XMLNODE ),
	string_table::svt( "Mouse", NSV::CLASS_MOUSE ),
	string_table::svt( "Object", NSV::CLASS_OBJECT ),
	string_table::svt( "String", NSV::CLASS_STRING ),
	string_table::svt( "Number", NSV::CLASS_NUMBER ),
	string_table::svt( "Accessibility", NSV::CLASS_ACCESSIBILITY ),	
	string_table::svt( "Array", NSV::CLASS_ARRAY ),
	string_table::svt( "Key", NSV::CLASS_KEY ),
	string_table::svt( "AsBroadcaster", NSV::CLASS_AS_BROADCASTER ),
	string_table::svt( "Function", NSV::CLASS_FUNCTION ),
	string_table::svt( "TextSnapshot", NSV::CLASS_TEXT_SNAPSHOT ),
	string_table::svt( "TextFormat", NSV::CLASS_TEXT_FORMAT ),
	string_table::svt( "Video", NSV::CLASS_VIDEO ),
	string_table::svt( "Camera", NSV::CLASS_CAMERA ),
	string_table::svt( "Microphone", NSV::CLASS_MICROPHONE ),
	string_table::svt( "SharedObject", NSV::CLASS_SHARED_OBJECT ),
	string_table::svt( "LoadVars", NSV::CLASS_LOAD_VARS ),
	string_table::svt( "LocalConnection", NSV::CLASS_LOCALCONNECTION ),
	string_table::svt( "CustomActions", NSV::CLASS_CUSTOM_ACTIONS ),
	string_table::svt( "NetConnection", NSV::CLASS_NET_CONNECTION ),
	string_table::svt( "NetStream", NSV::CLASS_NET_STREAM ),
	string_table::svt( "ContextMenu", NSV::CLASS_CONTEXTMENU ),
	string_table::svt( "MovieClipLoader", NSV::CLASS_MOVIE_CLIP_LOADER ),
	string_table::svt( "Error", NSV::CLASS_ERROR ),
	string_table::svt( "EventDispatcher", NSV::CLASS_EVENTDISPATCHER),
	string_table::svt( "DisplayObject", NSV::CLASS_DISPLAYOBJECT),
	string_table::svt( "InteractiveObject", NSV::CLASS_INTERACTIVEOBJECT ),
	string_table::svt( "DisplayObjectContainer", NSV::CLASS_DISPLAYOBJECTCONTAINER ),
	string_table::svt( "Sprite", NSV::CLASS_SPRITE ),
	string_table::svt( "int", NSV::CLASS_INT ),
	string_table::svt( "TextFieldAutoSize", NSV::CLASS_TEXTFIELDAUTOSIZE),
#else
	string_table::svt("AccessibilityProperties", NSV::CLASS_ACCESSIBILITYPROPERTIES),
	string_table::svt("Accessibility", NSV::CLASS_ACCESSIBILITY),
	string_table::svt("EncryptedLocalStore", NSV::CLASS_ENCRYPTEDLOCALSTORE),
	string_table::svt("SQLCollationType", NSV::CLASS_SQLCOLLATIONTYPE),
	string_table::svt("SQLColumnNameStyle", NSV::CLASS_SQLCOLUMNNAMESTYLE),
	string_table::svt("SQLColumnSchema", NSV::CLASS_SQLCOLUMNSCHEMA),
	string_table::svt("SQLConnection", NSV::CLASS_SQLCONNECTION),
	string_table::svt("SQLIndexSchema", NSV::CLASS_SQLINDEXSCHEMA),
	string_table::svt("SQLMode", NSV::CLASS_SQLMODE),
	string_table::svt("SQLResult", NSV::CLASS_SQLRESULT),
	string_table::svt("SQLSchemaResult", NSV::CLASS_SQLSCHEMARESULT),
	string_table::svt("SQLSchema", NSV::CLASS_SQLSCHEMA),
	string_table::svt("SQLStatement", NSV::CLASS_SQLSTATEMENT),
	string_table::svt("SQLTableSchema", NSV::CLASS_SQLTABLESCHEMA),
	string_table::svt("SQLTransactionLockType", NSV::CLASS_SQLTRANSACTIONLOCKTYPE),
	string_table::svt("SQLTriggerSchema", NSV::CLASS_SQLTRIGGERSCHEMA),
	string_table::svt("SQLViewSchema", NSV::CLASS_SQLVIEWSCHEMA),
	string_table::svt("ClipboardFormats", NSV::CLASS_CLIPBOARDFORMATS),
	string_table::svt("ClipboardTransferMode", NSV::CLASS_CLIPBOARDTRANSFERMODE),
	string_table::svt("Clipboard", NSV::CLASS_CLIPBOARD),
	string_table::svt("DockIcon", NSV::CLASS_DOCKICON),
	string_table::svt("EncryptedLocalStore", NSV::CLASS_ENCRYPTEDLOCALSTORE),
	string_table::svt("Icon", NSV::CLASS_ICON),
	string_table::svt("InteractiveIcon", NSV::CLASS_INTERACTIVEICON),
	string_table::svt("NativeApplication", NSV::CLASS_NATIVEAPPLICATION),
	string_table::svt("NativeDragActions", NSV::CLASS_NATIVEDRAGACTIONS),
	string_table::svt("NativeDragManager", NSV::CLASS_NATIVEDRAGMANAGER),
	string_table::svt("NativeDragOptions", NSV::CLASS_NATIVEDRAGOPTIONS),
	string_table::svt("NotificationType", NSV::CLASS_NOTIFICATIONTYPE),
	string_table::svt("SystemTrayIcon", NSV::CLASS_SYSTEMTRAYICON),
	string_table::svt("Updater", NSV::CLASS_UPDATER),
	string_table::svt("AVM1Movie", NSV::CLASS_AVM1MOVIE),
	string_table::svt("ActionScriptVersion", NSV::CLASS_ACTIONSCRIPTVERSION),
	string_table::svt("BitmapDataChannel", NSV::CLASS_BITMAPDATACHANNEL),
	string_table::svt("BitmapData", NSV::CLASS_BITMAPDATA),
	string_table::svt("Bitmap", NSV::CLASS_BITMAP),
	string_table::svt("BlendMode", NSV::CLASS_BLENDMODE),
	string_table::svt("CapsStyle", NSV::CLASS_CAPSSTYLE),
	string_table::svt("DisplayObjectContainer", NSV::CLASS_DISPLAYOBJECTCONTAINER),
	string_table::svt("DisplayObject", NSV::CLASS_DISPLAYOBJECT),
	string_table::svt("FocusDirection", NSV::CLASS_FOCUSDIRECTION),
	string_table::svt("FrameLabel", NSV::CLASS_FRAMELABEL),
	string_table::svt("GradientType", NSV::CLASS_GRADIENTTYPE),
	string_table::svt("Graphics", NSV::CLASS_GRAPHICS),
	string_table::svt("IBitmapDrawable", NSV::CLASS_IBITMAPDRAWABLE),
	string_table::svt("InteractiveObject", NSV::CLASS_INTERACTIVEOBJECT),
	string_table::svt("InterpolationMethod", NSV::CLASS_INTERPOLATIONMETHOD),
	string_table::svt("JointStyle", NSV::CLASS_JOINTSTYLE),
	string_table::svt("LineScaleMode", NSV::CLASS_LINESCALEMODE),
	string_table::svt("LoaderInfo", NSV::CLASS_LOADERINFO),
	string_table::svt("Loader", NSV::CLASS_LOADER),
	string_table::svt("MorphShape", NSV::CLASS_MORPHSHAPE),
	string_table::svt("MovieClip", NSV::CLASS_MOVIECLIP),
	string_table::svt("NativeMenuItem", NSV::CLASS_NATIVEMENUITEM),
	string_table::svt("NativeMenu", NSV::CLASS_NATIVEMENU),
	string_table::svt("NativeWindowDisplayState", NSV::CLASS_NATIVEWINDOWDISPLAYSTATE),
	string_table::svt("NativeWindowInitOptions", NSV::CLASS_NATIVEWINDOWINITOPTIONS),
	string_table::svt("NativeWindowResize", NSV::CLASS_NATIVEWINDOWRESIZE),
	string_table::svt("NativeWindowType", NSV::CLASS_NATIVEWINDOWTYPE),
	string_table::svt("NativeWindow", NSV::CLASS_NATIVEWINDOW),
	string_table::svt("PixelSnapping", NSV::CLASS_PIXELSNAPPING),
	string_table::svt("SWFVersion", NSV::CLASS_SWFVERSION),
	string_table::svt("Scene", NSV::CLASS_SCENE),
	string_table::svt("Screen", NSV::CLASS_SCREEN),
	string_table::svt("Shape", NSV::CLASS_SHAPE),
	string_table::svt("SimpleButton", NSV::CLASS_SIMPLEBUTTON),
	string_table::svt("SpreadMethod", NSV::CLASS_SPREADMETHOD),
	string_table::svt("Sprite", NSV::CLASS_SPRITE),
	string_table::svt("StageAlign", NSV::CLASS_STAGEALIGN),
	string_table::svt("StageDisplayState", NSV::CLASS_STAGEDISPLAYSTATE),
	string_table::svt("StageQuality", NSV::CLASS_STAGEQUALITY),
	string_table::svt("StageScaleMode", NSV::CLASS_STAGESCALEMODE),
	string_table::svt("Stage", NSV::CLASS_STAGE),
	string_table::svt("EOFError", NSV::CLASS_EOFERROR),
	string_table::svt("IOError", NSV::CLASS_IOERROR),
	string_table::svt("IllegalOperationError", NSV::CLASS_ILLEGALOPERATIONERROR),
	string_table::svt("InvalidSWFError", NSV::CLASS_INVALIDSWFERROR),
	string_table::svt("MemoryError", NSV::CLASS_MEMORYERROR),
	string_table::svt("SQLErrorOperation", NSV::CLASS_SQLERROROPERATION),
	string_table::svt("SQLError", NSV::CLASS_SQLERROR),
	string_table::svt("ScriptTimeoutError", NSV::CLASS_SCRIPTTIMEOUTERROR),
	string_table::svt("StackOverflowError", NSV::CLASS_STACKOVERFLOWERROR),
	string_table::svt("ActivityEvent", NSV::CLASS_ACTIVITYEVENT),
	string_table::svt("AsyncErrorEvent", NSV::CLASS_ASYNCERROREVENT),
	string_table::svt("BrowserInvokeEvent", NSV::CLASS_BROWSERINVOKEEVENT),
	string_table::svt("ContextMenuEvent", NSV::CLASS_CONTEXTMENUEVENT),
	string_table::svt("DRMAuthenticateEvent", NSV::CLASS_DRMAUTHENTICATEEVENT),
	string_table::svt("DRMErrorEvent", NSV::CLASS_DRMERROREVENT),
	string_table::svt("DRMStatusEvent", NSV::CLASS_DRMSTATUSEVENT),
	string_table::svt("DataEvent", NSV::CLASS_DATAEVENT),
	string_table::svt("ErrorEvent", NSV::CLASS_ERROREVENT),
	string_table::svt("EventDispatcher", NSV::CLASS_EVENTDISPATCHER),
	string_table::svt("EventPhase", NSV::CLASS_EVENTPHASE),
	string_table::svt("Event", NSV::CLASS_EVENT),
	string_table::svt("FileListEvent", NSV::CLASS_FILELISTEVENT),
	string_table::svt("FocusEvent", NSV::CLASS_FOCUSEVENT),
	string_table::svt("FullScreenEvent", NSV::CLASS_FULLSCREENEVENT),
	string_table::svt("HTMLUncaughtScriptExceptionEvent", NSV::CLASS_HTMLUNCAUGHTSCRIPTEXCEPTIONEVENT),
	string_table::svt("HTTPStatusEvent", NSV::CLASS_HTTPSTATUSEVENT),
	string_table::svt("IEventDispatcher", NSV::CLASS_IEVENTDISPATCHER),
	string_table::svt("IMEEvent", NSV::CLASS_IMEEVENT),
	string_table::svt("IOErrorEvent", NSV::CLASS_IOERROREVENT),
	string_table::svt("InvokeEvent", NSV::CLASS_INVOKEEVENT),
	string_table::svt("KeyboardEvent", NSV::CLASS_KEYBOARDEVENT),
	string_table::svt("MouseEvent", NSV::CLASS_MOUSEEVENT),
	string_table::svt("NativeDragEvent", NSV::CLASS_NATIVEDRAGEVENT),
	string_table::svt("NativeWindowBoundsEvent", NSV::CLASS_NATIVEWINDOWBOUNDSEVENT),
	string_table::svt("NativeWindowDisplayStateEvent", NSV::CLASS_NATIVEWINDOWDISPLAYSTATEEVENT),
	string_table::svt("NetStatusEvent", NSV::CLASS_NETSTATUSEVENT),
	string_table::svt("OutputProgressEvent", NSV::CLASS_OUTPUTPROGRESSEVENT),
	string_table::svt("ProgressEvent", NSV::CLASS_PROGRESSEVENT),
	string_table::svt("SQLErrorEvent", NSV::CLASS_SQLERROREVENT),
	string_table::svt("SQLEvent", NSV::CLASS_SQLEVENT),
	string_table::svt("SQLUpdateEvent", NSV::CLASS_SQLUPDATEEVENT),
	string_table::svt("ScreenMouseEvent", NSV::CLASS_SCREENMOUSEEVENT),
	string_table::svt("SecurityErrorEvent", NSV::CLASS_SECURITYERROREVENT),
	string_table::svt("StatusEvent", NSV::CLASS_STATUSEVENT),
	string_table::svt("SyncEvent", NSV::CLASS_SYNCEVENT),
	string_table::svt("TextEvent", NSV::CLASS_TEXTEVENT),
	string_table::svt("TimerEvent", NSV::CLASS_TIMEREVENT),
	string_table::svt("ExternalInterface", NSV::CLASS_EXTERNALINTERFACE),
	string_table::svt("FileMode", NSV::CLASS_FILEMODE),
	string_table::svt("FileStream", NSV::CLASS_FILESTREAM),
	string_table::svt("File", NSV::CLASS_FILE),
	string_table::svt("BevelFilter", NSV::CLASS_BEVELFILTER),
	string_table::svt("BitmapFilterQuality", NSV::CLASS_BITMAPFILTERQUALITY),
	string_table::svt("BitmapFilterType", NSV::CLASS_BITMAPFILTERTYPE),
	string_table::svt("BitmapFilter", NSV::CLASS_BITMAPFILTER),
	string_table::svt("BlurFilter", NSV::CLASS_BLURFILTER),
	string_table::svt("ColorMatrixFilter", NSV::CLASS_COLORMATRIXFILTER),
	string_table::svt("ConvolutionFilter", NSV::CLASS_CONVOLUTIONFILTER),
	string_table::svt("DisplacementMapFilterMode", NSV::CLASS_DISPLACEMENTMAPFILTERMODE),
	string_table::svt("DisplacementMapFilter", NSV::CLASS_DISPLACEMENTMAPFILTER),
	string_table::svt("DropShadowFilter", NSV::CLASS_DROPSHADOWFILTER),
	string_table::svt("GlowFilter", NSV::CLASS_GLOWFILTER),
	string_table::svt("GradientBevelFilter", NSV::CLASS_GRADIENTBEVELFILTER),
	string_table::svt("GradientGlowFilter", NSV::CLASS_GRADIENTGLOWFILTER),
	string_table::svt("ColorTransform", NSV::CLASS_COLORTRANSFORM),
	string_table::svt("Matrix", NSV::CLASS_MATRIX),
	string_table::svt("Point", NSV::CLASS_POINT),
	string_table::svt("Rectangle", NSV::CLASS_RECTANGLE),
	string_table::svt("Transform", NSV::CLASS_TRANSFORM),
	string_table::svt("HTMLHistoryItem", NSV::CLASS_HTMLHISTORYITEM),
	string_table::svt("HTMLHost", NSV::CLASS_HTMLHOST),
	string_table::svt("HTMLLoader", NSV::CLASS_HTMLLOADER),
	string_table::svt("HTMLPDFCapability", NSV::CLASS_HTMLPDFCAPABILITY),
	string_table::svt("HTMLWindowCreateOptions", NSV::CLASS_HTMLWINDOWCREATEOPTIONS),
	string_table::svt("Camera", NSV::CLASS_CAMERA),
	string_table::svt("ID3Info", NSV::CLASS_ID3INFO),
	string_table::svt("Microphone", NSV::CLASS_MICROPHONE),
	string_table::svt("SoundChannel", NSV::CLASS_SOUNDCHANNEL),
	string_table::svt("SoundLoaderContext", NSV::CLASS_SOUNDLOADERCONTEXT),
	string_table::svt("SoundMixer", NSV::CLASS_SOUNDMIXER),
	string_table::svt("SoundTransform", NSV::CLASS_SOUNDTRANSFORM),
	string_table::svt("Sound", NSV::CLASS_SOUND),
	string_table::svt("Video", NSV::CLASS_VIDEO),
	string_table::svt("FileFilter", NSV::CLASS_FILEFILTER),
	string_table::svt("FileReferenceList", NSV::CLASS_FILEREFERENCELIST),
	string_table::svt("FileReference", NSV::CLASS_FILEREFERENCE),
	string_table::svt("IDynamicPropertyOutput", NSV::CLASS_IDYNAMICPROPERTYOUTPUT),
	string_table::svt("IDynamicPropertyWriter", NSV::CLASS_IDYNAMICPROPERTYWRITER),
	string_table::svt("LocalConnection", NSV::CLASS_LOCALCONNECTION),
	string_table::svt("NetConnection", NSV::CLASS_NETCONNECTION),
	string_table::svt("NetStream", NSV::CLASS_NETSTREAM),
	string_table::svt("ObjectEncoding", NSV::CLASS_OBJECTENCODING),
	string_table::svt("Responder", NSV::CLASS_RESPONDER),
	string_table::svt("SharedObjectFlushStatus", NSV::CLASS_SHAREDOBJECTFLUSHSTATUS),
	string_table::svt("SharedObject", NSV::CLASS_SHAREDOBJECT),
	string_table::svt("Socket", NSV::CLASS_SOCKET),
	string_table::svt("URLLoaderDataFormat", NSV::CLASS_URLLOADERDATAFORMAT),
	string_table::svt("URLLoader", NSV::CLASS_URLLOADER),
	string_table::svt("URLRequestDefaults", NSV::CLASS_URLREQUESTDEFAULTS),
	string_table::svt("URLRequestHeader", NSV::CLASS_URLREQUESTHEADER),
	string_table::svt("URLRequestMethod", NSV::CLASS_URLREQUESTMETHOD),
	string_table::svt("URLRequest", NSV::CLASS_URLREQUEST),
	string_table::svt("URLStream", NSV::CLASS_URLSTREAM),
	string_table::svt("URLVariables", NSV::CLASS_URLVARIABLES),
	string_table::svt("XMLSocket", NSV::CLASS_XMLSOCKET),
	string_table::svt("PrintJobOptions", NSV::CLASS_PRINTJOBOPTIONS),
	string_table::svt("PrintJobOrientation", NSV::CLASS_PRINTJOBORIENTATION),
	string_table::svt("PrintJob", NSV::CLASS_PRINTJOB),
	string_table::svt("DeleteObjectSample", NSV::CLASS_DELETEOBJECTSAMPLE),
	string_table::svt("NewObjectSample", NSV::CLASS_NEWOBJECTSAMPLE),
	string_table::svt("Sample", NSV::CLASS_SAMPLE),
	string_table::svt("StackFrame", NSV::CLASS_STACKFRAME),
	string_table::svt("IURIDereferencer", NSV::CLASS_IURIDEREFERENCER),
	string_table::svt("RevocationCheckSettings", NSV::CLASS_REVOCATIONCHECKSETTINGS),
	string_table::svt("SignatureStatus", NSV::CLASS_SIGNATURESTATUS),
	string_table::svt("SignerTrustSettings", NSV::CLASS_SIGNERTRUSTSETTINGS),
	string_table::svt("XMLSignatureValidator", NSV::CLASS_XMLSIGNATUREVALIDATOR),
	string_table::svt("ApplicationDomain", NSV::CLASS_APPLICATIONDOMAIN),
	string_table::svt("Capabilities", NSV::CLASS_CAPABILITIES),
	string_table::svt("IMEConversionMode", NSV::CLASS_IMECONVERSIONMODE),
	string_table::svt("IME", NSV::CLASS_IME),
	string_table::svt("LoaderContext", NSV::CLASS_LOADERCONTEXT),
	string_table::svt("SecurityDomain", NSV::CLASS_SECURITYDOMAIN),
	string_table::svt("SecurityPanel", NSV::CLASS_SECURITYPANEL),
	string_table::svt("Security", NSV::CLASS_SECURITY),
	string_table::svt("System", NSV::CLASS_SYSTEM),
	string_table::svt("AntiAliasType", NSV::CLASS_ANTIALIASTYPE),
	string_table::svt("CSMSettings", NSV::CLASS_CSMSETTINGS),
	string_table::svt("FontStyle", NSV::CLASS_FONTSTYLE),
	string_table::svt("FontType", NSV::CLASS_FONTTYPE),
	string_table::svt("Font", NSV::CLASS_FONT),
	string_table::svt("GridFitType", NSV::CLASS_GRIDFITTYPE),
	string_table::svt("StaticText", NSV::CLASS_STATICTEXT),
	string_table::svt("StyleSheet", NSV::CLASS_STYLESHEET),
	string_table::svt("TextColorType", NSV::CLASS_TEXTCOLORTYPE),
	string_table::svt("TextDisplayMode", NSV::CLASS_TEXTDISPLAYMODE),
	string_table::svt("TextFieldAutoSize", NSV::CLASS_TEXTFIELDAUTOSIZE),
	string_table::svt("TextFieldType", NSV::CLASS_TEXTFIELDTYPE),
	string_table::svt("TextField", NSV::CLASS_TEXTFIELD),
	string_table::svt("TextFormatAlign", NSV::CLASS_TEXTFORMATALIGN),
	string_table::svt("TextFormat", NSV::CLASS_TEXTFORMAT),
	string_table::svt("TextLineMetrics", NSV::CLASS_TEXTLINEMETRICS),
	string_table::svt("TextRenderer", NSV::CLASS_TEXTRENDERER),
	string_table::svt("TextSnapshot", NSV::CLASS_TEXTSNAPSHOT),
	string_table::svt("ContextMenuBuiltInItems", NSV::CLASS_CONTEXTMENUBUILTINITEMS),
	string_table::svt("ContextMenuItem", NSV::CLASS_CONTEXTMENUITEM),
	string_table::svt("ContextMenu", NSV::CLASS_CONTEXTMENU),
	string_table::svt("KeyLocation", NSV::CLASS_KEYLOCATION),
	string_table::svt("Keyboard", NSV::CLASS_KEYBOARD),
	string_table::svt("Mouse", NSV::CLASS_MOUSE),
	string_table::svt("ByteArray", NSV::CLASS_BYTEARRAY),
	string_table::svt("CompressionAlgorithm", NSV::CLASS_COMPRESSIONALGORITHM),
	string_table::svt("Dictionary", NSV::CLASS_DICTIONARY),
	string_table::svt("Endian", NSV::CLASS_ENDIAN),
	string_table::svt("IDataInput", NSV::CLASS_IDATAINPUT),
	string_table::svt("IDataOutput", NSV::CLASS_IDATAOUTPUT),
	string_table::svt("IExternalizable", NSV::CLASS_IEXTERNALIZABLE),
	string_table::svt("Proxy", NSV::CLASS_PROXY),
	string_table::svt("Timer", NSV::CLASS_TIMER),
	string_table::svt("XMLDocument", NSV::CLASS_XMLDOCUMENT),
	string_table::svt("XMLNodeType", NSV::CLASS_XMLNODETYPE),
	string_table::svt("XMLNode", NSV::CLASS_XMLNODE),
#endif
	string_table::svt( "flash.accessibility", NSV::NS_FLASH_ACCESSIBILITY),
	string_table::svt( "flash.data", NSV::NS_FLASH_DATA ),
	string_table::svt( "flash.desktop", NSV::NS_FLASH_DESKTOP),
	string_table::svt( "flash.display", NSV::NS_FLASH_DISPLAY),
	string_table::svt( "flash.erros", NSV::NS_FLASH_ERRORS),
	string_table::svt( "flash.events", NSV::NS_FLASH_EVENTS),
	string_table::svt( "flash.external", NSV::NS_FLASH_EXTERNAL),
	string_table::svt( "flash.filesystem", NSV::NS_FLASH_FILESYSTEM),
	string_table::svt( "flash.filters", NSV::NS_FLASH_FILTERS),
	string_table::svt( "flash.geom", NSV::NS_FLASH_GEOM),
	string_table::svt( "flash.html", NSV::NS_FLASH_HTML),
	string_table::svt( "flash.media", NSV::NS_FLASH_MEDIA),
	string_table::svt( "flash.net", NSV::NS_FLASH_NET),
	string_table::svt( "flash.printing", NSV::NS_FLASH_PRINTING),
	string_table::svt( "flash.sampler", NSV::NS_FLASH_SAMPLER),
	string_table::svt( "flash.system", NSV::NS_FLASH_SYSTEM),
	string_table::svt( "flash.security", NSV::NS_FLASH_SECURITY),
	string_table::svt( "flash.text", NSV::NS_FLASH_TEXT),
	string_table::svt( "flash.utils", NSV::NS_FLASH_UTILS),
	string_table::svt( "flash.ui", NSV::NS_FLASH_UI),
	string_table::svt( "adobe.utils", NSV::NS_ADOBE_UTILS),
	string_table::svt( "flash.xml", NSV::NS_FLASH_XML),
	string_table::svt( "", NSV::INTERNAL_TYPE),
	string_table::svt( "", NSV::INTERNAL_STACK_PARENT),
	string_table::svt( "", NSV::INTERNAL_INTERFACES)
};

void loadStrings(string_table &table, int version)
{
	if (version < 7)
	{
		table.set_insensitive();
	}

	table.insert_group(preload_names,
		sizeof (preload_names) / sizeof (string_table::svt));
}

} // namespace NSV
} // namespace gnash
