// Generated by Makefile, don't hand edit!
#ifndef GNASH_ASOBJ_FLASH_UTILS_H
#define GNASH_ASOBJ_FLASH_UTILS_H 1
#include "sharedlib.h"
static gnash::SharedLib::initentry *as3utilsclasses[] = {
	gnash::bytearray_class_init,
	gnash::dictionary_class_init,
	gnash::endian_class_init,
	gnash::idatainput_class_init,
	gnash::idataoutput_class_init,
	gnash::iexternalizable_class_init,
	gnash::proxy_class_init,
	gnash::timer_class_init,
	0
};
#endif // end of GNASH_ASOBJ_FLASH_UTILS_H
