// ContextMenuBuiltInItems_as.hx:  ActionScript 3 "ContextMenuBuiltInItems" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.ui.ContextMenuBuiltInItems;
import flash.display.MovieClip;
#else
import flash.ContextMenuBuiltInItems;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class ContextMenuBuiltInItems_as {
    static function main() {
        var x1:ContextMenuBuiltInItems = new ContextMenuBuiltInItems();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("ContextMenuBuiltInItems class exists");
        } else {
            DejaGnu.fail("ContextMenuBuiltInItems class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.forwardAndBack == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.forwardAndBack property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.forwardAndBack property doesn't exist");
	}
	if (x1.loop == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.loop property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.loop property doesn't exist");
	}
	if (x1.play == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.play property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.play property doesn't exist");
	}
	if (x1.print == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.print property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.print property doesn't exist");
	}
	if (x1.quality == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.quality property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.quality property doesn't exist");
	}
	if (x1.rewind == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.rewind property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.rewind property doesn't exist");
	}
	if (x1.save == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.save property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.save property doesn't exist");
	}
	if (x1.zoom == false) {
	    DejaGnu.pass("ContextMenuBuiltInItems.zoom property exists");
	} else {
	    DejaGnu.fail("ContextMenuBuiltInItems.zoom property doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

