// Generated by Makefile, don't hand edit!
#ifndef GNASH_ASOBJ_FLASH_DISPLAY_H
#define GNASH_ASOBJ_FLASH_DISPLAY_H 1
#include "sharedlib.h"
static gnash::SharedLib::initentry *displayclasses[] = {
	0
};
#endif // end of GNASH_ASOBJ_FLASH_DISPLAY_H
