// URLLoader_as.hx:  ActionScript 3 "URLLoader" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090514 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.net.URLLoader;
import flash.display.MovieClip;
#else
import flash.URLLoader;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class URLLoader_as {
    static function main() {
        var x1:URLLoader = new URLLoader();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("URLLoader class exists");
        } else {
            DejaGnu.fail("URLLoader class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.bytesLoaded == 0) {
	    DejaGnu.pass("URLLoader.bytesLoaded property exists");
	} else {
	    DejaGnu.fail("URLLoader.bytesLoaded property doesn't exist");
	}
	if (x1.bytesTotal == 0) {
	    DejaGnu.pass("URLLoader.bytesTotal property exists");
	} else {
	    DejaGnu.fail("URLLoader.bytesTotal property doesn't exist");
	}
	if (x1.data == 0) {
	    DejaGnu.pass("URLLoader.data property exists");
	} else {
	    DejaGnu.fail("URLLoader.data property doesn't exist");
	}
	if (x1.dataFormat == null) {
	    DejaGnu.pass("URLLoader.dataFormat property exists");
	} else {
	    DejaGnu.fail("URLLoader.dataFormat property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
// 	if (x1.URLLoader == URLRequest) {
// 	    DejaGnu.pass("URLLoader::URLLoader() method exists");
// 	} else {
// 	    DejaGnu.fail("URLLoader::URLLoader() method doesn't exist");
// 	}
	if (x1.addEventListener == null) {
	    DejaGnu.pass("URLLoader::addEventListener() method exists");
	} else {
	    DejaGnu.fail("URLLoader::addEventListener() method doesn't exist");
	}
	if (x1.close == null) {
	    DejaGnu.pass("URLLoader::close() method exists");
	} else {
	    DejaGnu.fail("URLLoader::close() method doesn't exist");
	}
	if (x1.load == null) {
	    DejaGnu.pass("URLLoader::load() method exists");
	} else {
	    DejaGnu.fail("URLLoader::load() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

