.TH gnash 1 "$Date: 2006/10/17 07:51:51 $" "$Author: nihilus $" \" -*- $Id: gnash.1,v 1.4 2006/10/17 07:51:51 nihilus Exp $ -*-
.SH NAME
gnash \- GNU Flash Player
.SH SYNOPSIS
.B gnash 
[options] movie_file.swf
.SH DESCRIPTION
.BR gnash 
is a GNU project to create a free software player and web browser 
(Mozilla-based and Konqueror) plugin for the Adobe Flash format. Currently the 
player can play Flash files, called SWF, up to version 7. Most other free 
software Flash players can only play up to SWF 4.
.SH OPTIONS
.TP 
\-h \--help
Print usage info.
.TP 
\-s factor
Scale the movie up/down by the specified factor.
.TP 
\-c
Produce a core file instead of letting SDL trap it
.TP 
\-d num
Number of milli\-seconds to delay in main loop
.TP 
\-v
Be verbose; i.e. print log messages to stdout
.TP 
\-va
Be verbose about movie Actions
.TP 
\-vp
Be verbose about parsing the movie
.TP 
\-m bias
Specify the texture LOD bias (float, default is \-1.0)
.TP
\-x ID
X11 Window ID for display
\-w
Produce the disk based debug log
\-j width
Set window width
\-k height
Set window height
.TP 
\-1
Play once; exit when/if movie reaches the last frame
.TP 
\-r [0|1|2|3]
0 disables renderering and sound (good for batch tests)

1 enables rendering & disables sound (default)

2 enables sound & disables rendering

3 enables both rendering & sound
.TP 
\-t sec
Timeout and exit after the specified number of seconds
.TP 
\-b bits
Bit depth of output window (16 or 32, default is 16)
.TP 
\-u url
Set "real" url of the movie (useful for downloaded movies)
.TP 
\-U url
Set "base" url for this run (used to resolve relative urls, defaults to movie 
url)
.TP 
\-P param
Set parameter (ie. "FlashVars=A=1&b=2")
.TP 
\--version
Print 
\fBgnash\fP's version number and exit
.SH KEYS
.TP 
CTRL\-Q
Quit/Exit
.TP 
CTRL\-W
Quit/Exit
.TP 
ESC
Quit/Exit
.TP 
CTRL\-P
Toggle Pause
.TP 
CTRL\-R 
Restart the movie
.TP 
CTRL\-[ or kp\-
Step back one frame
.TP 
CTRL\-] or kp+
Step forward one frame
.TP 
CTRL\-B
Toggle background color
.SH "BUGS"
The best way to report a bug is to use the form at
http://savannah.gnu.org/bugs/?group=gnash.  
The reason for this is that you will then be able to track progress in
fixing the problem. Other comments about \fBgnash\fP(1) in general can be sent to the 
.I gnash
mailing list.  To join the list, send email to 
.IR gnash-request@gnu.org .
