// HTMLWindowCreateOptions_as.hx:  ActionScript 3 "HTMLWindowCreateOptions" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009, 2010 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.html.HTMLWindowCreateOptions;
import flash.display.MovieClip;
#else
import flash.HTMLWindowCreateOptions;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class HTMLWindowCreateOptions_as {
    static function main() {
        var x1:HTMLWindowCreateOptions = new HTMLWindowCreateOptions();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("HTMLWindowCreateOptions class exists");
        } else {
            DejaGnu.fail("HTMLWindowCreateOptions class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.fullscreen == false) {
	    DejaGnu.pass("HTMLWindowCreateOptions.fullscreen property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.fullscreen property doesn't exist");
	}
	if (x1.height == 0) {
	    DejaGnu.pass("HTMLWindowCreateOptions.height property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.height property doesn't exist");
	}
	if (x1.locationBarVisible == false) {
	    DejaGnu.pass("HTMLWindowCreateOptions.locationBarVisible property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.locationBarVisible property doesn't exist");
	}
	if (x1.menuBarVisible == false) {
	    DejaGnu.pass("HTMLWindowCreateOptions.menuBarVisible property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.menuBarVisible property doesn't exist");
	}
	if (x1.resizable == false) {
	    DejaGnu.pass("HTMLWindowCreateOptions.resizable property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.resizable property doesn't exist");
	}
	if (x1.scrollBarsVisible == false) {
	    DejaGnu.pass("HTMLWindowCreateOptions.scrollBarsVisible property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.scrollBarsVisible property doesn't exist");
	}
	if (x1.statusBarVisible == false) {
	    DejaGnu.pass("HTMLWindowCreateOptions.statusBarVisible property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.statusBarVisible property doesn't exist");
	}
	if (x1.toolBarVisible == false) {
	    DejaGnu.pass("HTMLWindowCreateOptions.toolBarVisible property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.toolBarVisible property doesn't exist");
	}
	if (x1.width == 0) {
	    DejaGnu.pass("HTMLWindowCreateOptions.width property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.width property doesn't exist");
	}
	if (x1.x == 0) {
	    DejaGnu.pass("HTMLWindowCreateOptions.x property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.x property doesn't exist");
	}
	if (x1.y == 0) {
	    DejaGnu.pass("HTMLWindowCreateOptions.y property exists");
	} else {
	    DejaGnu.fail("HTMLWindowCreateOptions.y property doesn't exist");
	}

	if (x1.fullscreen == false) {
        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

