#!/bin/sh 

# Get this from environment if available, or use a default working
# when invoked by build-dir.
# Better yet might be generating this file on make check..
#
GPROCESSOR=${GPROCESSOR:=../../utilities/gprocessor}

if [ -z "$1" ]; then
	echo "Usage: `basename $0` <swffile>" >&2
	exit 1
fi

echo "Using gprocessor ${GPROCESSOR}"

in="$1"
out=`basename "${in}"`.trace-gnash
use_orig=0
exp="${in}.trace"
if [ -e "${in}.trace.org" ]; then
	exp="${in}.trace.org"
	use_orig=1
fi

# NOTE: We're supposed to advance 10 frames.
#       We advance 11 times as for Gnash the first call to ::advance
#       simply constructs the root movie (will be fixed eventually)
#
${GPROCESSOR} -r11 -f11 -v "$in"  | grep TRACE | sed 's/.*TRACE: //' | fromdos > $out
if test "$?" != 0; then
	echo "gprocessor returned an error"
	exit 1
else
	if [ "$use_orig" != 0 ]; then
		awk 'BEGIN {body=0;} { if (body) { print $0} else if (/^$/) {body=1} }' "$exp" | diff -u3 - "$out"
		exit $?
	else
		diff -u3 "$exp" "$out"
		exit $?
	fi
fi
