// Timer_as.hx:  ActionScript 3 "Timer" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.utils.Timer;
import flash.display.MovieClip;
#else
import flash.Timer;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class Timer_as {
    static function main() {
        var x1:Timer = new Timer();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("Timer class exists");
        } else {
            DejaGnu.fail("Timer class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.currentCount == 0) {
	    DejaGnu.pass("Timer.currentCount property exists");
	} else {
	    DejaGnu.fail("Timer.currentCount property doesn't exist");
	}
	if (x1.delay == 0) {
	    DejaGnu.pass("Timer.delay property exists");
	} else {
	    DejaGnu.fail("Timer.delay property doesn't exist");
	}
	if (x1.repeatCount == 0) {
	    DejaGnu.pass("Timer.repeatCount property exists");
	} else {
	    DejaGnu.fail("Timer.repeatCount property doesn't exist");
	}
	if (x1.running == false) {
	    DejaGnu.pass("Timer.running property exists");
	} else {
	    DejaGnu.fail("Timer.running property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.Timer == 0) {
	    DejaGnu.pass("Timer::Timer() method exists");
	} else {
	    DejaGnu.fail("Timer::Timer() method doesn't exist");
	}
	if (x1.reset == null) {
	    DejaGnu.pass("Timer::reset() method exists");
	} else {
	    DejaGnu.fail("Timer::reset() method doesn't exist");
	}
	if (x1.start == null) {
	    DejaGnu.pass("Timer::start() method exists");
	} else {
	    DejaGnu.fail("Timer::start() method doesn't exist");
	}
	if (x1.stop == null) {
	    DejaGnu.pass("Timer::stop() method exists");
	} else {
	    DejaGnu.fail("Timer::stop() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

