// Generated by Makefile, don't hand edit!
#ifndef GNASH_ASOBJ_FLASH_ERRORS_H
#define GNASH_ASOBJ_FLASH_ERRORS_H 1
#include "sharedlib.h"
static gnash::SharedLib::initentry *as3errorsclasses[] = {
	gnash::eoferror_class_init,
	gnash::ioerror_class_init,
	gnash::illegaloperationerror_class_init,
	gnash::invalidswferror_class_init,
	gnash::memoryerror_class_init,
	gnash::scripttimeouterror_class_init,
	gnash::stackoverflowerror_class_init,
	0
};
#endif // end of GNASH_ASOBJ_FLASH_ERRORS_H
