// Generated by Makefile, don't hand edit!
#ifndef GNASH_ASOBJ_FLASH_NET_H
#define GNASH_ASOBJ_FLASH_NET_H 1
#include "sharedlib.h"
static gnash::SharedLib::initentry *netclasses[] = {
    gnash::filereference_class_init,
    0
};
#endif // end of GNASH_ASOBJ_FLASH_NET_H
