// XMLNode_as.hx:  ActionScript 3 "XMLNode" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090514 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.xml.XMLNode;
import flash.xml.XMLNodeType;
import flash.display.MovieClip;
#else
import flash.XMLNode;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class XMLNode_as {
    static function main() {
        var x1:XMLNode = new XMLNode(XMLNodeType.ELEMENT_NODE, null);

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("XMLNode class exists");
        } else {
            DejaGnu.fail("XMLNode class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
// 	if (x1.attributes == Object) {
// 	    DejaGnu.pass("XMLNode.attributes property exists");
// 	} else {
// 	    DejaGnu.fail("XMLNode.attributes property doesn't exist");
// 	}
// FIXME: returns an array
// 	if (x1.childNodes == 0) {
// 	    DejaGnu.pass("XMLNode.childNodes property exists");
// 	} else {
// 	    DejaGnu.fail("XMLNode.childNodes property doesn't exist");
// 	}
	if (x1.localName == null) {
	    DejaGnu.pass("XMLNode.localName property exists");
	} else {
	    DejaGnu.fail("XMLNode.localName property doesn't exist");
	}
	if (x1.namespaceURI == null) {
	    DejaGnu.pass("XMLNode.namespaceURI property exists");
	} else {
	    DejaGnu.fail("XMLNode.namespaceURI property doesn't exist");
	}
	if (x1.nextSibling == x1.nextSibling) {
	    DejaGnu.pass("XMLNode.nextSibling property exists");
	} else {
	    DejaGnu.fail("XMLNode.nextSibling property doesn't exist");
	}
	if (x1.nodeName == null) {
	    DejaGnu.pass("XMLNode.nodeName property exists");
	} else {
	    DejaGnu.fail("XMLNode.nodeName property doesn't exist");
	}
// FIXME: Int should be flash.xml.XMLNodeType
// 	if (x1.nodeType == 0) {
// 	    DejaGnu.pass("XMLNode.nodeType property exists");
// 	} else {
// 	    DejaGnu.fail("XMLNode.nodeType property doesn't exist");
// 	}
	if (x1.nodeValue == null) {
	    DejaGnu.pass("XMLNode.nodeValue property exists");
	} else {
	    DejaGnu.fail("XMLNode.nodeValue property doesn't exist");
	}
// 	if (x1.parentNode == parentNode) {
// 	    DejaGnu.pass("XMLNode.parentNode property exists");
// 	} else {
// 	    DejaGnu.fail("XMLNode.parentNode property doesn't exist");
// 	}
	if (x1.prefix == null) {
	    DejaGnu.pass("XMLNode.prefix property exists");
	} else {
	    DejaGnu.fail("XMLNode.prefix property doesn't exist");
	}
// 	if (x1.previousSibling == previousSibling) {
// 	    DejaGnu.pass("XMLNode.previousSibling property exists");
// 	} else {
// 	    DejaGnu.fail("XMLNode.previousSibling property doesn't exist");
// 	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.appendChild == null) {
	    DejaGnu.pass("XMLNode::appendChild() method exists");
	} else {
	    DejaGnu.fail("XMLNode::appendChild() method doesn't exist");
	}
// 	if (x1.cloneNode == XMLNode) {
// 	    DejaGnu.pass("XMLNode::cloneNode() method exists");
// 	} else {
// 	    DejaGnu.fail("XMLNode::cloneNode() method doesn't exist");
// 	}
	if (x1.getNamespaceForPrefix == null) {
	    DejaGnu.pass("XMLNode::getNamespaceForPrefix() method exists");
	} else {
	    DejaGnu.fail("XMLNode::getNamespaceForPrefix() method doesn't exist");
	}
	if (x1.getPrefixForNamespace == null) {
	    DejaGnu.pass("XMLNode::getPrefixForNamespace() method exists");
	} else {
	    DejaGnu.fail("XMLNode::getPrefixForNamespace() method doesn't exist");
	}
// FIXME:  Bool should be Void -> Bool
// 	if (x1.hasChildNodes == false) {
// 	    DejaGnu.pass("XMLNode::hasChildNodes() method exists");
// 	} else {
// 	    DejaGnu.fail("XMLNode::hasChildNodes() method doesn't exist");
// 	}
	if (x1.insertBefore == null) {
	    DejaGnu.pass("XMLNode::insertBefore() method exists");
	} else {
	    DejaGnu.fail("XMLNode::insertBefore() method doesn't exist");
	}
	if (x1.removeNode == null) {
	    DejaGnu.pass("XMLNode::removeNode() method exists");
	} else {
	    DejaGnu.fail("XMLNode::removeNode() method doesn't exist");
	}
	if (x1.toString == null) {
	    DejaGnu.pass("XMLNode::toString() method exists");
	} else {
	    DejaGnu.fail("XMLNode::toString() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

