// DropShadowFilter_as3.hx:  ActionScript 3 "DropShadowFilter" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.filters.DropShadowFilter;
import flash.display.MovieClip;
#else
import flash.DropShadowFilter;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as3 suffix, as that's the same name as the file.
class DropShadowFilter_as3 {
    static function main() {
        var x1:DropShadowFilter = new DropShadowFilter();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("DropShadowFilter class exists");
        } else {
            DejaGnu.fail("DropShadowFilter class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.alpha == 0) {
	    DejaGnu.pass("DropShadowFilter.alpha property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.alpha property doesn't exist");
	}
	if (x1.angle == 0) {
	    DejaGnu.pass("DropShadowFilter.angle property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.angle property doesn't exist");
	}
	if (x1.blurX == 0) {
	    DejaGnu.pass("DropShadowFilter.blurX property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.blurX property doesn't exist");
	}
	if (x1.blurY == 0) {
	    DejaGnu.pass("DropShadowFilter.blurY property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.blurY property doesn't exist");
	}
	if (x1.color == uint) {
	    DejaGnu.pass("DropShadowFilter.color property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.color property doesn't exist");
	}
	if (x1.distance == 0) {
	    DejaGnu.pass("DropShadowFilter.distance property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.distance property doesn't exist");
	}
	if (x1.hideObject == false) {
	    DejaGnu.pass("DropShadowFilter.hideObject property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.hideObject property doesn't exist");
	}
	if (x1.inner == false) {
	    DejaGnu.pass("DropShadowFilter.inner property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.inner property doesn't exist");
	}
	if (x1.knockout == false) {
	    DejaGnu.pass("DropShadowFilter.knockout property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.knockout property doesn't exist");
	}
	if (x1.quality == 0) {
	    DejaGnu.pass("DropShadowFilter.quality property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.quality property doesn't exist");
	}
	if (x1.strength == 0) {
	    DejaGnu.pass("DropShadowFilter.strength property exists");
	} else {
	    DejaGnu.fail("DropShadowFilter.strength property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.DropShadowFilter == false) {
	    DejaGnu.pass("DropShadowFilter::DropShadowFilter() method exists");
	} else {
	    DejaGnu.fail("DropShadowFilter::DropShadowFilter() method doesn't exist");
	}
	if (x1.clone == BitmapFilter) {
	    DejaGnu.pass("DropShadowFilter::clone() method exists");
	} else {
	    DejaGnu.fail("DropShadowFilter::clone() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

