// GradientGlowFilter_as.hx:  ActionScript 3 "GradientGlowFilter" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.filters.GradientGlowFilter;
import flash.display.MovieClip;
#else
import flash.GradientGlowFilter;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class GradientGlowFilter_as {
    static function main() {
        var x1:GradientGlowFilter = new GradientGlowFilter();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("GradientGlowFilter class exists");
        } else {
            DejaGnu.fail("GradientGlowFilter class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.alphas == 0) {
	    DejaGnu.pass("GradientGlowFilter.alphas property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.alphas property doesn't exist");
	}
	if (x1.angle == 0) {
	    DejaGnu.pass("GradientGlowFilter.angle property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.angle property doesn't exist");
	}
	if (x1.blurX == 0) {
	    DejaGnu.pass("GradientGlowFilter.blurX property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.blurX property doesn't exist");
	}
	if (x1.blurY == 0) {
	    DejaGnu.pass("GradientGlowFilter.blurY property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.blurY property doesn't exist");
	}
	if (x1.colors == 0) {
	    DejaGnu.pass("GradientGlowFilter.colors property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.colors property doesn't exist");
	}
	if (x1.distance == 0) {
	    DejaGnu.pass("GradientGlowFilter.distance property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.distance property doesn't exist");
	}
	if (x1.knockout == false) {
	    DejaGnu.pass("GradientGlowFilter.knockout property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.knockout property doesn't exist");
	}
	if (x1.quality == 0) {
	    DejaGnu.pass("GradientGlowFilter.quality property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.quality property doesn't exist");
	}
	if (x1.ratios == 0) {
	    DejaGnu.pass("GradientGlowFilter.ratios property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.ratios property doesn't exist");
	}
	if (x1.strength == 0) {
	    DejaGnu.pass("GradientGlowFilter.strength property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.strength property doesn't exist");
	}
	if (x1.type == null) {
	    DejaGnu.pass("GradientGlowFilter.type property exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter.type property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.GradientGlowFilter == false) {
	    DejaGnu.pass("GradientGlowFilter::GradientGlowFilter() method exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter::GradientGlowFilter() method doesn't exist");
	}
	if (x1.clone == BitmapFilter) {
	    DejaGnu.pass("GradientGlowFilter::clone() method exists");
	} else {
	    DejaGnu.fail("GradientGlowFilter::clone() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

