// AsyncErrorEvent_as.hx:  ActionScript 3 "AsyncErrorEvent" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.events.AsyncErrorEvent;
import flash.display.MovieClip;
#else
import flash.AsyncErrorEvent;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class AsyncErrorEvent_as {
    static function main() {
        var x1:AsyncErrorEvent = new AsyncErrorEvent();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("AsyncErrorEvent class exists");
        } else {
            DejaGnu.fail("AsyncErrorEvent class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.error == Error) {
	    DejaGnu.pass("AsyncErrorEvent.error property exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent.error property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.AsyncErrorEvent == Error) {
	    DejaGnu.pass("AsyncErrorEvent::AsyncErrorEvent() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::AsyncErrorEvent() method doesn't exist");
	}
	if (x1.clone == Event) {
	    DejaGnu.pass("AsyncErrorEvent::clone() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::clone() method doesn't exist");
	}
	if (x1.toString == null) {
	    DejaGnu.pass("AsyncErrorEvent::toString() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::toString() method doesn't exist");
	}
	if (x1.ACTIVATE == null) {
	    DejaGnu.pass("AsyncErrorEvent::ACTIVATE() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::ACTIVATE() method doesn't exist");
	}
	if (x1.ADDED == null) {
	    DejaGnu.pass("AsyncErrorEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::ADDED() method doesn't exist");
	}
	if (x1.ADDED == TO) {
	    DejaGnu.pass("AsyncErrorEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::ADDED() method doesn't exist");
	}
	if (x1.ASYNC == ERROR) {
	    DejaGnu.pass("AsyncErrorEvent::ASYNC() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::ASYNC() method doesn't exist");
	}
	if (x1.CANCEL == null) {
	    DejaGnu.pass("AsyncErrorEvent::CANCEL() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::CANCEL() method doesn't exist");
	}
	if (x1.CHANGE == null) {
	    DejaGnu.pass("AsyncErrorEvent::CHANGE() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::CHANGE() method doesn't exist");
	}
	if (x1.CLOSE == null) {
	    DejaGnu.pass("AsyncErrorEvent::CLOSE() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::CLOSE() method doesn't exist");
	}
	if (x1.CLOSING == null) {
	    DejaGnu.pass("AsyncErrorEvent::CLOSING() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::CLOSING() method doesn't exist");
	}
	if (x1.COMPLETE == null) {
	    DejaGnu.pass("AsyncErrorEvent::COMPLETE() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::COMPLETE() method doesn't exist");
	}
	if (x1.CONNECT == null) {
	    DejaGnu.pass("AsyncErrorEvent::CONNECT() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::CONNECT() method doesn't exist");
	}
	if (x1.DEACTIVATE == null) {
	    DejaGnu.pass("AsyncErrorEvent::DEACTIVATE() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::DEACTIVATE() method doesn't exist");
	}
	if (x1.DISPLAYING == null) {
	    DejaGnu.pass("AsyncErrorEvent::DISPLAYING() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::DISPLAYING() method doesn't exist");
	}
	if (x1.ENTER == FRAME) {
	    DejaGnu.pass("AsyncErrorEvent::ENTER() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::ENTER() method doesn't exist");
	}
	if (x1.ERROR == null) {
	    DejaGnu.pass("AsyncErrorEvent::ERROR() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::ERROR() method doesn't exist");
	}
	if (x1.EXITING == null) {
	    DejaGnu.pass("AsyncErrorEvent::EXITING() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::EXITING() method doesn't exist");
	}
	if (x1.FULLSCREEN == null) {
	    DejaGnu.pass("AsyncErrorEvent::FULLSCREEN() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::FULLSCREEN() method doesn't exist");
	}
	if (x1.HTML == BOUNDS) {
	    DejaGnu.pass("AsyncErrorEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == DOM) {
	    DejaGnu.pass("AsyncErrorEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == RENDER) {
	    DejaGnu.pass("AsyncErrorEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::HTML() method doesn't exist");
	}
	if (x1.ID3 == null) {
	    DejaGnu.pass("AsyncErrorEvent::ID3() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::ID3() method doesn't exist");
	}
	if (x1.INIT == null) {
	    DejaGnu.pass("AsyncErrorEvent::INIT() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::INIT() method doesn't exist");
	}
	if (x1.LINK == null) {
	    DejaGnu.pass("AsyncErrorEvent::LINK() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::LINK() method doesn't exist");
	}
	if (x1.LOCATION == CHANGE) {
	    DejaGnu.pass("AsyncErrorEvent::LOCATION() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::LOCATION() method doesn't exist");
	}
	if (x1.MOUSE == LEAVE) {
	    DejaGnu.pass("AsyncErrorEvent::MOUSE() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::MOUSE() method doesn't exist");
	}
	if (x1.NETWORK == CHANGE) {
	    DejaGnu.pass("AsyncErrorEvent::NETWORK() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::NETWORK() method doesn't exist");
	}
	if (x1.OPEN == null) {
	    DejaGnu.pass("AsyncErrorEvent::OPEN() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::OPEN() method doesn't exist");
	}
	if (x1.REMOVED == null) {
	    DejaGnu.pass("AsyncErrorEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::REMOVED() method doesn't exist");
	}
	if (x1.REMOVED == FROM) {
	    DejaGnu.pass("AsyncErrorEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::REMOVED() method doesn't exist");
	}
	if (x1.RENDER == null) {
	    DejaGnu.pass("AsyncErrorEvent::RENDER() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::RENDER() method doesn't exist");
	}
	if (x1.RESIZE == null) {
	    DejaGnu.pass("AsyncErrorEvent::RESIZE() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::RESIZE() method doesn't exist");
	}
	if (x1.SCROLL == null) {
	    DejaGnu.pass("AsyncErrorEvent::SCROLL() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::SCROLL() method doesn't exist");
	}
	if (x1.SELECT == null) {
	    DejaGnu.pass("AsyncErrorEvent::SELECT() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::SELECT() method doesn't exist");
	}
	if (x1.SOUND == COMPLETE) {
	    DejaGnu.pass("AsyncErrorEvent::SOUND() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::SOUND() method doesn't exist");
	}
	if (x1.TAB == CHILDREN) {
	    DejaGnu.pass("AsyncErrorEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == ENABLED) {
	    DejaGnu.pass("AsyncErrorEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == INDEX) {
	    DejaGnu.pass("AsyncErrorEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::TAB() method doesn't exist");
	}
	if (x1.TEXT == INPUT) {
	    DejaGnu.pass("AsyncErrorEvent::TEXT() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::TEXT() method doesn't exist");
	}
	if (x1.UNLOAD == null) {
	    DejaGnu.pass("AsyncErrorEvent::UNLOAD() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::UNLOAD() method doesn't exist");
	}
	if (x1.USER == IDLE) {
	    DejaGnu.pass("AsyncErrorEvent::USER() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::USER() method doesn't exist");
	}
	if (x1.USER == PRESENT) {
	    DejaGnu.pass("AsyncErrorEvent::USER() method exists");
	} else {
	    DejaGnu.fail("AsyncErrorEvent::USER() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

