// HTTPStatusEvent_as.hx:  ActionScript 3 "HTTPStatusEvent" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.events.HTTPStatusEvent;
import flash.display.MovieClip;
#else
import flash.HTTPStatusEvent;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class HTTPStatusEvent_as {
    static function main() {
        var x1:HTTPStatusEvent = new HTTPStatusEvent();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("HTTPStatusEvent class exists");
        } else {
            DejaGnu.fail("HTTPStatusEvent class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.responseHeaders == 0) {
	    DejaGnu.pass("HTTPStatusEvent.responseHeaders property exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent.responseHeaders property doesn't exist");
	}
	if (x1.responseURL == null) {
	    DejaGnu.pass("HTTPStatusEvent.responseURL property exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent.responseURL property doesn't exist");
	}
	if (x1.status == 0) {
	    DejaGnu.pass("HTTPStatusEvent.status property exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent.status property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.HTTPStatusEvent == 0) {
	    DejaGnu.pass("HTTPStatusEvent::HTTPStatusEvent() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::HTTPStatusEvent() method doesn't exist");
	}
	if (x1.clone == Event) {
	    DejaGnu.pass("HTTPStatusEvent::clone() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::clone() method doesn't exist");
	}
	if (x1.toString == null) {
	    DejaGnu.pass("HTTPStatusEvent::toString() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::toString() method doesn't exist");
	}
	if (x1.ACTIVATE == null) {
	    DejaGnu.pass("HTTPStatusEvent::ACTIVATE() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::ACTIVATE() method doesn't exist");
	}
	if (x1.ADDED == null) {
	    DejaGnu.pass("HTTPStatusEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::ADDED() method doesn't exist");
	}
	if (x1.ADDED == TO) {
	    DejaGnu.pass("HTTPStatusEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::ADDED() method doesn't exist");
	}
	if (x1.CANCEL == null) {
	    DejaGnu.pass("HTTPStatusEvent::CANCEL() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::CANCEL() method doesn't exist");
	}
	if (x1.CHANGE == null) {
	    DejaGnu.pass("HTTPStatusEvent::CHANGE() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::CHANGE() method doesn't exist");
	}
	if (x1.CLOSE == null) {
	    DejaGnu.pass("HTTPStatusEvent::CLOSE() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::CLOSE() method doesn't exist");
	}
	if (x1.CLOSING == null) {
	    DejaGnu.pass("HTTPStatusEvent::CLOSING() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::CLOSING() method doesn't exist");
	}
	if (x1.COMPLETE == null) {
	    DejaGnu.pass("HTTPStatusEvent::COMPLETE() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::COMPLETE() method doesn't exist");
	}
	if (x1.CONNECT == null) {
	    DejaGnu.pass("HTTPStatusEvent::CONNECT() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::CONNECT() method doesn't exist");
	}
	if (x1.DEACTIVATE == null) {
	    DejaGnu.pass("HTTPStatusEvent::DEACTIVATE() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::DEACTIVATE() method doesn't exist");
	}
	if (x1.DISPLAYING == null) {
	    DejaGnu.pass("HTTPStatusEvent::DISPLAYING() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::DISPLAYING() method doesn't exist");
	}
	if (x1.ENTER == FRAME) {
	    DejaGnu.pass("HTTPStatusEvent::ENTER() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::ENTER() method doesn't exist");
	}
	if (x1.EXITING == null) {
	    DejaGnu.pass("HTTPStatusEvent::EXITING() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::EXITING() method doesn't exist");
	}
	if (x1.FULLSCREEN == null) {
	    DejaGnu.pass("HTTPStatusEvent::FULLSCREEN() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::FULLSCREEN() method doesn't exist");
	}
	if (x1.HTML == BOUNDS) {
	    DejaGnu.pass("HTTPStatusEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == DOM) {
	    DejaGnu.pass("HTTPStatusEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == RENDER) {
	    DejaGnu.pass("HTTPStatusEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::HTML() method doesn't exist");
	}
	if (x1.HTTP == RESPONSE) {
	    DejaGnu.pass("HTTPStatusEvent::HTTP() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::HTTP() method doesn't exist");
	}
	if (x1.HTTP == STATUS) {
	    DejaGnu.pass("HTTPStatusEvent::HTTP() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::HTTP() method doesn't exist");
	}
	if (x1.ID3 == null) {
	    DejaGnu.pass("HTTPStatusEvent::ID3() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::ID3() method doesn't exist");
	}
	if (x1.INIT == null) {
	    DejaGnu.pass("HTTPStatusEvent::INIT() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::INIT() method doesn't exist");
	}
	if (x1.LOCATION == CHANGE) {
	    DejaGnu.pass("HTTPStatusEvent::LOCATION() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::LOCATION() method doesn't exist");
	}
	if (x1.MOUSE == LEAVE) {
	    DejaGnu.pass("HTTPStatusEvent::MOUSE() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::MOUSE() method doesn't exist");
	}
	if (x1.NETWORK == CHANGE) {
	    DejaGnu.pass("HTTPStatusEvent::NETWORK() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::NETWORK() method doesn't exist");
	}
	if (x1.OPEN == null) {
	    DejaGnu.pass("HTTPStatusEvent::OPEN() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::OPEN() method doesn't exist");
	}
	if (x1.REMOVED == null) {
	    DejaGnu.pass("HTTPStatusEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::REMOVED() method doesn't exist");
	}
	if (x1.REMOVED == FROM) {
	    DejaGnu.pass("HTTPStatusEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::REMOVED() method doesn't exist");
	}
	if (x1.RENDER == null) {
	    DejaGnu.pass("HTTPStatusEvent::RENDER() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::RENDER() method doesn't exist");
	}
	if (x1.RESIZE == null) {
	    DejaGnu.pass("HTTPStatusEvent::RESIZE() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::RESIZE() method doesn't exist");
	}
	if (x1.SCROLL == null) {
	    DejaGnu.pass("HTTPStatusEvent::SCROLL() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::SCROLL() method doesn't exist");
	}
	if (x1.SELECT == null) {
	    DejaGnu.pass("HTTPStatusEvent::SELECT() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::SELECT() method doesn't exist");
	}
	if (x1.SOUND == COMPLETE) {
	    DejaGnu.pass("HTTPStatusEvent::SOUND() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::SOUND() method doesn't exist");
	}
	if (x1.TAB == CHILDREN) {
	    DejaGnu.pass("HTTPStatusEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == ENABLED) {
	    DejaGnu.pass("HTTPStatusEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == INDEX) {
	    DejaGnu.pass("HTTPStatusEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::TAB() method doesn't exist");
	}
	if (x1.UNLOAD == null) {
	    DejaGnu.pass("HTTPStatusEvent::UNLOAD() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::UNLOAD() method doesn't exist");
	}
	if (x1.USER == IDLE) {
	    DejaGnu.pass("HTTPStatusEvent::USER() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::USER() method doesn't exist");
	}
	if (x1.USER == PRESENT) {
	    DejaGnu.pass("HTTPStatusEvent::USER() method exists");
	} else {
	    DejaGnu.fail("HTTPStatusEvent::USER() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

