// InvokeEvent_as3.hx:  ActionScript 3 "InvokeEvent" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.events.InvokeEvent;
import flash.display.MovieClip;
#else
import flash.InvokeEvent;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as3 suffix, as that's the same name as the file.
class InvokeEvent_as3 {
    static function main() {
        var x1:InvokeEvent = new InvokeEvent();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("InvokeEvent class exists");
        } else {
            DejaGnu.fail("InvokeEvent class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.arguments == 0) {
	    DejaGnu.pass("InvokeEvent.arguments property exists");
	} else {
	    DejaGnu.fail("InvokeEvent.arguments property doesn't exist");
	}
	if (x1.currentDirectory == File) {
	    DejaGnu.pass("InvokeEvent.currentDirectory property exists");
	} else {
	    DejaGnu.fail("InvokeEvent.currentDirectory property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.InvokeEvent == 0) {
	    DejaGnu.pass("InvokeEvent::InvokeEvent() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::InvokeEvent() method doesn't exist");
	}
	if (x1.clone == Event) {
	    DejaGnu.pass("InvokeEvent::clone() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::clone() method doesn't exist");
	}
	if (x1.ACTIVATE == null) {
	    DejaGnu.pass("InvokeEvent::ACTIVATE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::ACTIVATE() method doesn't exist");
	}
	if (x1.ADDED == null) {
	    DejaGnu.pass("InvokeEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::ADDED() method doesn't exist");
	}
	if (x1.ADDED == TO) {
	    DejaGnu.pass("InvokeEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::ADDED() method doesn't exist");
	}
	if (x1.CANCEL == null) {
	    DejaGnu.pass("InvokeEvent::CANCEL() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::CANCEL() method doesn't exist");
	}
	if (x1.CHANGE == null) {
	    DejaGnu.pass("InvokeEvent::CHANGE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::CHANGE() method doesn't exist");
	}
	if (x1.CLOSE == null) {
	    DejaGnu.pass("InvokeEvent::CLOSE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::CLOSE() method doesn't exist");
	}
	if (x1.CLOSING == null) {
	    DejaGnu.pass("InvokeEvent::CLOSING() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::CLOSING() method doesn't exist");
	}
	if (x1.COMPLETE == null) {
	    DejaGnu.pass("InvokeEvent::COMPLETE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::COMPLETE() method doesn't exist");
	}
	if (x1.CONNECT == null) {
	    DejaGnu.pass("InvokeEvent::CONNECT() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::CONNECT() method doesn't exist");
	}
	if (x1.DEACTIVATE == null) {
	    DejaGnu.pass("InvokeEvent::DEACTIVATE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::DEACTIVATE() method doesn't exist");
	}
	if (x1.DISPLAYING == null) {
	    DejaGnu.pass("InvokeEvent::DISPLAYING() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::DISPLAYING() method doesn't exist");
	}
	if (x1.ENTER == FRAME) {
	    DejaGnu.pass("InvokeEvent::ENTER() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::ENTER() method doesn't exist");
	}
	if (x1.EXITING == null) {
	    DejaGnu.pass("InvokeEvent::EXITING() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::EXITING() method doesn't exist");
	}
	if (x1.FULLSCREEN == null) {
	    DejaGnu.pass("InvokeEvent::FULLSCREEN() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::FULLSCREEN() method doesn't exist");
	}
	if (x1.HTML == BOUNDS) {
	    DejaGnu.pass("InvokeEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == DOM) {
	    DejaGnu.pass("InvokeEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == RENDER) {
	    DejaGnu.pass("InvokeEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::HTML() method doesn't exist");
	}
	if (x1.ID3 == null) {
	    DejaGnu.pass("InvokeEvent::ID3() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::ID3() method doesn't exist");
	}
	if (x1.INIT == null) {
	    DejaGnu.pass("InvokeEvent::INIT() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::INIT() method doesn't exist");
	}
	if (x1.INVOKE == null) {
	    DejaGnu.pass("InvokeEvent::INVOKE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::INVOKE() method doesn't exist");
	}
	if (x1.LOCATION == CHANGE) {
	    DejaGnu.pass("InvokeEvent::LOCATION() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::LOCATION() method doesn't exist");
	}
	if (x1.MOUSE == LEAVE) {
	    DejaGnu.pass("InvokeEvent::MOUSE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::MOUSE() method doesn't exist");
	}
	if (x1.NETWORK == CHANGE) {
	    DejaGnu.pass("InvokeEvent::NETWORK() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::NETWORK() method doesn't exist");
	}
	if (x1.OPEN == null) {
	    DejaGnu.pass("InvokeEvent::OPEN() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::OPEN() method doesn't exist");
	}
	if (x1.REMOVED == null) {
	    DejaGnu.pass("InvokeEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::REMOVED() method doesn't exist");
	}
	if (x1.REMOVED == FROM) {
	    DejaGnu.pass("InvokeEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::REMOVED() method doesn't exist");
	}
	if (x1.RENDER == null) {
	    DejaGnu.pass("InvokeEvent::RENDER() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::RENDER() method doesn't exist");
	}
	if (x1.RESIZE == null) {
	    DejaGnu.pass("InvokeEvent::RESIZE() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::RESIZE() method doesn't exist");
	}
	if (x1.SCROLL == null) {
	    DejaGnu.pass("InvokeEvent::SCROLL() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::SCROLL() method doesn't exist");
	}
	if (x1.SELECT == null) {
	    DejaGnu.pass("InvokeEvent::SELECT() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::SELECT() method doesn't exist");
	}
	if (x1.SOUND == COMPLETE) {
	    DejaGnu.pass("InvokeEvent::SOUND() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::SOUND() method doesn't exist");
	}
	if (x1.TAB == CHILDREN) {
	    DejaGnu.pass("InvokeEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == ENABLED) {
	    DejaGnu.pass("InvokeEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == INDEX) {
	    DejaGnu.pass("InvokeEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::TAB() method doesn't exist");
	}
	if (x1.UNLOAD == null) {
	    DejaGnu.pass("InvokeEvent::UNLOAD() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::UNLOAD() method doesn't exist");
	}
	if (x1.USER == IDLE) {
	    DejaGnu.pass("InvokeEvent::USER() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::USER() method doesn't exist");
	}
	if (x1.USER == PRESENT) {
	    DejaGnu.pass("InvokeEvent::USER() method exists");
	} else {
	    DejaGnu.fail("InvokeEvent::USER() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

