// StatusEvent_as.hx:  ActionScript 3 "StatusEvent" class, for Gnash.
//
// Generated by gen-as3.sh on: 20090515 by "rob". Remove this
// after any hand editing loosing changes.
//
//   Copyright (C) 2009 Free Software Foundation, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This test case must be processed by CPP before compiling to include the
//  DejaGnu.hx header file for the testing framework support.

#if flash9
import flash.events.StatusEvent;
import flash.display.MovieClip;
#else
import flash.StatusEvent;
import flash.MovieClip;
#end
import flash.Lib;
import Type;

// import our testing API
import DejaGnu;

// Class must be named with the _as suffix, as that's the same name as the file.
class StatusEvent_as {
    static function main() {
        var x1:StatusEvent = new StatusEvent();

        // Make sure we actually get a valid class        
        if (x1 != null) {
            DejaGnu.pass("StatusEvent class exists");
        } else {
            DejaGnu.fail("StatusEvent class doesn't exist");
        }
// Tests to see if all the properties exist. All these do is test for
// existance of a property, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.code == null) {
	    DejaGnu.pass("StatusEvent.code property exists");
	} else {
	    DejaGnu.fail("StatusEvent.code property doesn't exist");
	}
	if (x1.level == null) {
	    DejaGnu.pass("StatusEvent.level property exists");
	} else {
	    DejaGnu.fail("StatusEvent.level property doesn't exist");
	}

// Tests to see if all the methods exist. All these do is test for
// existance of a method, and don't test the functionality at all. This
// is primarily useful only to test completeness of the API implementation.
	if (x1.StatusEvent == null) {
	    DejaGnu.pass("StatusEvent::StatusEvent() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::StatusEvent() method doesn't exist");
	}
	if (x1.clone == Event) {
	    DejaGnu.pass("StatusEvent::clone() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::clone() method doesn't exist");
	}
	if (x1.toString == null) {
	    DejaGnu.pass("StatusEvent::toString() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::toString() method doesn't exist");
	}
	if (x1.ACTIVATE == null) {
	    DejaGnu.pass("StatusEvent::ACTIVATE() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::ACTIVATE() method doesn't exist");
	}
	if (x1.ADDED == null) {
	    DejaGnu.pass("StatusEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::ADDED() method doesn't exist");
	}
	if (x1.ADDED == TO) {
	    DejaGnu.pass("StatusEvent::ADDED() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::ADDED() method doesn't exist");
	}
	if (x1.CANCEL == null) {
	    DejaGnu.pass("StatusEvent::CANCEL() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::CANCEL() method doesn't exist");
	}
	if (x1.CHANGE == null) {
	    DejaGnu.pass("StatusEvent::CHANGE() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::CHANGE() method doesn't exist");
	}
	if (x1.CLOSE == null) {
	    DejaGnu.pass("StatusEvent::CLOSE() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::CLOSE() method doesn't exist");
	}
	if (x1.CLOSING == null) {
	    DejaGnu.pass("StatusEvent::CLOSING() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::CLOSING() method doesn't exist");
	}
	if (x1.COMPLETE == null) {
	    DejaGnu.pass("StatusEvent::COMPLETE() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::COMPLETE() method doesn't exist");
	}
	if (x1.CONNECT == null) {
	    DejaGnu.pass("StatusEvent::CONNECT() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::CONNECT() method doesn't exist");
	}
	if (x1.DEACTIVATE == null) {
	    DejaGnu.pass("StatusEvent::DEACTIVATE() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::DEACTIVATE() method doesn't exist");
	}
	if (x1.DISPLAYING == null) {
	    DejaGnu.pass("StatusEvent::DISPLAYING() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::DISPLAYING() method doesn't exist");
	}
	if (x1.ENTER == FRAME) {
	    DejaGnu.pass("StatusEvent::ENTER() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::ENTER() method doesn't exist");
	}
	if (x1.EXITING == null) {
	    DejaGnu.pass("StatusEvent::EXITING() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::EXITING() method doesn't exist");
	}
	if (x1.FULLSCREEN == null) {
	    DejaGnu.pass("StatusEvent::FULLSCREEN() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::FULLSCREEN() method doesn't exist");
	}
	if (x1.HTML == BOUNDS) {
	    DejaGnu.pass("StatusEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == DOM) {
	    DejaGnu.pass("StatusEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::HTML() method doesn't exist");
	}
	if (x1.HTML == RENDER) {
	    DejaGnu.pass("StatusEvent::HTML() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::HTML() method doesn't exist");
	}
	if (x1.ID3 == null) {
	    DejaGnu.pass("StatusEvent::ID3() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::ID3() method doesn't exist");
	}
	if (x1.INIT == null) {
	    DejaGnu.pass("StatusEvent::INIT() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::INIT() method doesn't exist");
	}
	if (x1.LOCATION == CHANGE) {
	    DejaGnu.pass("StatusEvent::LOCATION() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::LOCATION() method doesn't exist");
	}
	if (x1.MOUSE == LEAVE) {
	    DejaGnu.pass("StatusEvent::MOUSE() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::MOUSE() method doesn't exist");
	}
	if (x1.NETWORK == CHANGE) {
	    DejaGnu.pass("StatusEvent::NETWORK() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::NETWORK() method doesn't exist");
	}
	if (x1.OPEN == null) {
	    DejaGnu.pass("StatusEvent::OPEN() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::OPEN() method doesn't exist");
	}
	if (x1.REMOVED == null) {
	    DejaGnu.pass("StatusEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::REMOVED() method doesn't exist");
	}
	if (x1.REMOVED == FROM) {
	    DejaGnu.pass("StatusEvent::REMOVED() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::REMOVED() method doesn't exist");
	}
	if (x1.RENDER == null) {
	    DejaGnu.pass("StatusEvent::RENDER() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::RENDER() method doesn't exist");
	}
	if (x1.RESIZE == null) {
	    DejaGnu.pass("StatusEvent::RESIZE() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::RESIZE() method doesn't exist");
	}
	if (x1.SCROLL == null) {
	    DejaGnu.pass("StatusEvent::SCROLL() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::SCROLL() method doesn't exist");
	}
	if (x1.SELECT == null) {
	    DejaGnu.pass("StatusEvent::SELECT() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::SELECT() method doesn't exist");
	}
	if (x1.SOUND == COMPLETE) {
	    DejaGnu.pass("StatusEvent::SOUND() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::SOUND() method doesn't exist");
	}
	if (x1.STATUS == null) {
	    DejaGnu.pass("StatusEvent::STATUS() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::STATUS() method doesn't exist");
	}
	if (x1.TAB == CHILDREN) {
	    DejaGnu.pass("StatusEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == ENABLED) {
	    DejaGnu.pass("StatusEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::TAB() method doesn't exist");
	}
	if (x1.TAB == INDEX) {
	    DejaGnu.pass("StatusEvent::TAB() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::TAB() method doesn't exist");
	}
	if (x1.UNLOAD == null) {
	    DejaGnu.pass("StatusEvent::UNLOAD() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::UNLOAD() method doesn't exist");
	}
	if (x1.USER == IDLE) {
	    DejaGnu.pass("StatusEvent::USER() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::USER() method doesn't exist");
	}
	if (x1.USER == PRESENT) {
	    DejaGnu.pass("StatusEvent::USER() method exists");
	} else {
	    DejaGnu.fail("StatusEvent::USER() method doesn't exist");
	}

        // Call this after finishing all tests. It prints out the totals.
        DejaGnu.done();
    }
}

// local Variables:
// mode: C++
// indent-tabs-mode: t
// End:

